### ISSUE TITLE
Refactoring failed: badarg, {ann_type ... trace

### ISSUE THREAD

**Issue by zeeshanlakhani** [RefactoringTools/wrangler#62]
Trace: https://gist.github.com/zeeshanlakhani/69c5691270a61fe347e9

I was just attempting to rename Vars and Functions, but consistently received the stack trace.

I'm using emacs cocoa on 10.10 and though the fault is **most probably** on my side, any help is appreciated. If you need more information, let me know. Otherwise, the inspector calls and such are working, just not the refactor ones.

**Comment by zeeshanlakhani** [comment]
I've made some progress on fixing this issue, though, still finalizing some clarity involving various search paths and .hrl files. You can probably close this, thanks!

**Comment by simonjohnthompson** [comment]
Thanks!

Simon


> On 13 Jan 2015, at 21:29, Zeeshan Lakhani <notifications@github.com> wrote:
> 
> Closed #62 <https://github.com/RefactoringTools/wrangler/issues/62>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/RefactoringTools/wrangler/issues/62#event-218168534>.
> 

Simon Thompson | Professor of Logic and Computation 
School of Computing | University of Kent | Canterbury, CT2 7NF, UK
s.j.thompson@kent.ac.uk | M +44 7986 085754 | W www.cs.kent.ac.uk/~sjt

**Comment by leoliu** [comment]
isn't it better to close the issue with the commit?
