### ISSUE TITLE
OTP 18 support

### ISSUE THREAD

**Issue by optikfluffel** [RefactoringTools/wrangler#67]
Hi :smile_cat: 
We want to [update the Erlang version for Homebrew](https://github.com/Homebrew/homebrew/pull/41035) and wanted to know, if wrangler is ready or if there is anything missing, do you maybe need some help?
Thanks a ton :heart_decoration:

**Comment by rprimus** [comment]
Mon Jul 13 21:08:00 BST 2015

@optikfluffel - WRT brew,  would it somehow be possible to automate raising these types of 'issues' with all brew Formulae that use 'depends_on "erlang"' (when homebrew is ready for a new version of erlang)?

**Comment by optikfluffel** [comment]
@rprimus I'm not really sure if there's a way to automate this right now. Maybe I'll find some time during the weekend to look around.

**Comment by optikfluffel** [comment]
I couldn't build wrangler using OTP18, are there any plans to support it yet?

**Comment by huiqing** [comment]
I will take a look into this next week.

Regards,
Huiqing

Sent from my iPhone

On 30 Jul 2015, at 08:32, "Udo Kramer" <notifications@github.com<mailto:notifications@github.com>> wrote:


I couldn't build wrangler using OTP18, are there any plans to support it yet?

—
Reply to this email directly or view it on GitHub<https://github.com/RefactoringTools/wrangler/issues/67#issuecomment-126209449>.

NOTICE AND DISCLAIMER
This e-mail (including any attachments) is intended for the above-named person(s).  If you are not the intended recipient, notify the sender immediately, delete this email from your system and do not disclose or use for any purpose.  
 
We may monitor all incoming and outgoing emails in line with current legislation. We have taken steps to ensure that this email and attachments are free from any virus, but it remains your responsibility to ensure that viruses do not adversely affect you. 

EE Limited
Registered in England and Wales
Company Registered Number: 02382161
Registered Office Address: Trident Place, Mosquito Way, Hatfield, Hertfordshire, AL10 9BW.

**Comment by optikfluffel** [comment]
![Thanks](http://www.reactiongifs.com/wp-content/uploads/2013/10/thanks.gif)

**Comment by simonjohnthompson** [comment]
Hi, we just tried Wrangler on R18 on Mac OS X and it seems to build and run fine. What's the problem you are having?

**Comment by felixbuenemann** [comment]
I also had no issues compiling it on R18, although there were a few deprecation warnings.
